eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.27:8761/eureka/
      
server:
  port: 8767
  
spring:
  application:
    name: eshop-datalink-service

ribbon:
  ReadTimeout: 60000
  SocketTimeout: 60000
  ConnectTimeout: 60000